# Generated by Django 3.2.8 on 2024-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, max_length=100, unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
