# Generated by Django 3.2.8 on 2024-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID'),
        ),
    ]
