# Generated by Django 3.2.8 on 2024-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miya_Neyroplastik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Nafs_Diagnostikasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Psixoterapiya_Psixologiya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Ruhiy_Salomatlik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Sharq_Psixologiyasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Tabobat_Tibbiyot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Talim_Ruhiyat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=150, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
        ),
        migrations.RenameModel(
            old_name='Medias',
            new_name='Farzandim_Jigarbandim',
        ),
    ]
