# Generated by Django 3.2.8 on 2024-05-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_auto_20240528_2227'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='psixoterapiya_psixologiya',
            table='Psixoterapiya_Psixologiya',
        ),
    ]
