# Generated by Django 3.2.8 on 2024-05-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_alter_psixoterapiya_psixologiya_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tabobat_tibbiyot',
            table='Tabobat_Tibbiyot',
        ),
    ]
