# Generated by Django 3.2.8 on 2024-05-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_alter_tabobat_tibbiyot_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabobat_tibbiyot',
            options={'verbose_name': 'Tabobat_Tibbiyot'},
        ),
        migrations.AlterModelTable(
            name='tabobat_tibbiyot',
            table=None,
        ),
    ]
