# Generated by Django 3.2.8 on 2024-05-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_auto_20240529_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabobat_tibbiyot',
            options={'verbose_name': 'Tabobat_Tibbiyot', 'verbose_name_plural': 'Tabobat_Tibbiyot'},
        ),
    ]
