# Generated by Django 3.2.8 on 2024-05-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0007_alter_tabobat_tibbiyot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psixoterapiya_psixologiya',
            options={'verbose_name_plural': 'Psixoterapiya va psixologiya asoslari'},
        ),
        migrations.AlterModelTable(
            name='psixoterapiya_psixologiya',
            table=None,
        ),
    ]
