# Generated by Django 3.2.8 on 2024-05-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0008_auto_20240529_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psixoterapiya_psixologiya',
            options={'verbose_name': 'Psixoterapiya va psixologiya asoslari', 'verbose_name_plural': 'Psixoterapiya va psixologiya asoslari'},
        ),
    ]
