# Generated by Django 3.2.8 on 2024-05-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0009_alter_psixoterapiya_psixologiya_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farzandim_jigarbandim',
            options={'verbose_name': 'Farzandim va jigarbandim'},
        ),
        migrations.AlterModelOptions(
            name='miya_neyroplastik',
            options={'verbose_name': 'Miyaning neyroplastikligi va neyrobika', 'verbose_name_plural': 'Miyaning neyroplastikligi va neyrobika'},
        ),
        migrations.AlterModelOptions(
            name='nafs_diagnostikasi',
            options={'verbose_name': 'Nafs diagnostikasi', 'verbose_name_plural': 'Nafs diagnostikasi'},
        ),
        migrations.AlterModelOptions(
            name='ruhiy_salomatlik',
            options={'verbose_name': 'Ruhiy salomatlik', 'verbose_name_plural': 'Ruhiy salomatlik'},
        ),
        migrations.AlterModelOptions(
            name='sharq_psixologiyasi',
            options={'verbose_name': 'Sharq psixologiyasi va psixoterapiya', 'verbose_name_plural': 'Sharq psixologiyasi va psixoterapiya'},
        ),
        migrations.AlterModelOptions(
            name='tabobat_tibbiyot',
            options={'verbose_name': 'Tabobat va tibbiyotda mijoz va tepmerament ilmi', 'verbose_name_plural': 'Tabobat va tibbiyotda mijoz va tepmerament ilmi'},
        ),
        migrations.AlterModelOptions(
            name='talim_ruhiyat',
            options={'verbose_name': "Ta'lim va ruhiyat", 'verbose_name_plural': "Ta'lim va ruhiyat"},
        ),
    ]
