# Generated by Django 3.2.8 on 2024-05-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_auto_20240529_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(null=True, unique=True, verbose_name='Dars tartib raqami')),
                ('file_id', models.CharField(max_length=50, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=10, null=True, verbose_name='File Type')),
                ('caption', models.CharField(max_length=4000, null=True, verbose_name='Caption')),
            ],
            options={
                'verbose_name': 'Turli suhbatlar',
                'verbose_name_plural': 'Turli suhbatlar',
            },
        ),
        migrations.RenameModel(
            old_name='Nafs_Diagnostikasi',
            new_name='table_3',
        ),
        migrations.RenameModel(
            old_name='Talim_Ruhiyat',
            new_name='table_4',
        ),
        migrations.RenameModel(
            old_name='Farzandim_Jigarbandim',
            new_name='table_5',
        ),
        migrations.RenameModel(
            old_name='Ruhiy_Salomatlik',
            new_name='table_6',
        ),
        migrations.RenameModel(
            old_name='Miya_Neyroplastik',
            new_name='table_7',
        ),
        migrations.RenameModel(
            old_name='Sharq_Psixologiyasi',
            new_name='table_8',
        ),
        migrations.AlterModelOptions(
            name='table_3',
            options={'verbose_name': 'Miyaning neyroplastikligi va neyrobika', 'verbose_name_plural': 'Miyaning neyroplastikligi va neyrobika'},
        ),
        migrations.AlterModelOptions(
            name='table_6',
            options={'verbose_name': 'Nafs diagnostikasi', 'verbose_name_plural': 'Nafs diagnostikasi'},
        ),
        migrations.AlterModelOptions(
            name='table_7',
            options={'verbose_name': 'Sharq psixologiyasi va psixoterapiya', 'verbose_name_plural': 'Sharq psixologiyasi va psixoterapiya'},
        ),
        migrations.AlterModelOptions(
            name='table_8',
            options={'verbose_name': 'Ruhiy salomatlik', 'verbose_name_plural': 'Ruhiy salomatlik'},
        ),
    ]
