# Generated by Django 3.2.8 on 2024-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0015_auto_20240529_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_9',
            name='audio_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table_9',
            name='document_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table_9',
            name='photo_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table_9',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Video ID'),
        ),
    ]
